import 'package:flutter/material.dart';
import 'flutter_icon_data.dart';
  class Fontelico { Fontelico._(); 
static const IconData emo_happy = const FlutterIconData.fontelico(59392);
static const IconData emo_wink = const FlutterIconData.fontelico(59393);
static const IconData emo_wink2 = const FlutterIconData.fontelico(59411);
static const IconData emo_unhappy = const FlutterIconData.fontelico(59394);
static const IconData emo_sleep = const FlutterIconData.fontelico(59395);
static const IconData emo_thumbsup = const FlutterIconData.fontelico(59396);
static const IconData emo_devil = const FlutterIconData.fontelico(59397);
static const IconData emo_surprised = const FlutterIconData.fontelico(59398);
static const IconData emo_tongue = const FlutterIconData.fontelico(59399);
static const IconData emo_coffee = const FlutterIconData.fontelico(59400);
static const IconData emo_sunglasses = const FlutterIconData.fontelico(59401);
static const IconData emo_displeased = const FlutterIconData.fontelico(59402);
static const IconData emo_beer = const FlutterIconData.fontelico(59403);
static const IconData emo_grin = const FlutterIconData.fontelico(59404);
static const IconData emo_angry = const FlutterIconData.fontelico(59405);
static const IconData emo_saint = const FlutterIconData.fontelico(59406);
static const IconData emo_cry = const FlutterIconData.fontelico(59407);
static const IconData emo_shoot = const FlutterIconData.fontelico(59408);
static const IconData emo_squint = const FlutterIconData.fontelico(59409);
static const IconData emo_laugh = const FlutterIconData.fontelico(59410);
static const IconData spin1 = const FlutterIconData.fontelico(59440);
static const IconData spin2 = const FlutterIconData.fontelico(59441);
static const IconData spin3 = const FlutterIconData.fontelico(59442);
static const IconData spin4 = const FlutterIconData.fontelico(59444);
static const IconData spin5 = const FlutterIconData.fontelico(59448);
static const IconData spin6 = const FlutterIconData.fontelico(59449);
static const IconData firefox = const FlutterIconData.fontelico(59456);
static const IconData chrome = const FlutterIconData.fontelico(59457);
static const IconData opera = const FlutterIconData.fontelico(59458);
static const IconData ie = const FlutterIconData.fontelico(59459);
static const IconData crown = const FlutterIconData.fontelico(59460);
static const IconData crown_plus = const FlutterIconData.fontelico(59461);
static const IconData crown_minus = const FlutterIconData.fontelico(59462);
static const IconData marquee = const FlutterIconData.fontelico(59463);
}